### ISSUE TITLE
How to integrate Dialogflow with Microsoft Teams.

### ISSUE THREAD

**Issue by revs1** [GoogleCloudPlatform/dialogflow-integrations#43]
As I have noticed in official document, Teams integration is not part of built in integrations supported by Google. It being an independent integration, can someone help me with trusted third party organization to do the same?

**Comment by mekpavit** [comment]
@revs1 I did integrate the Dialogflow with Microsoft Teams about 4 months ago using the same approach as Skype. Have you tried integrating using the Skype approach mentioned [here](https://github.com/GoogleCloudPlatform/dialogflow-integrations/tree/master/skype).

**Comment by cah-prashanth-soma** [comment]
@mekpavit 
What will be the messaging endpoint configuration for the server.js. I am unable to access the bot from the Microsoft bot framework channel TEST.

I have tried appending both "/webhook" and "/api/messages" to the cloud function URL https://xxxxxxxx.cloudfunctions.net/TeamsChannel

I am trying to integrate teams. I have followed the documentation for skype open source. But, instead of docker containers i am using cloud functions to deploy the server.js. (org level restrictions on docker).

**Comment by mekpavit** [comment]
@cah-prashanth-soma Have you tried using the Cloud Function url with adding any suffix? I've never used Cloud Function for hosting the webhook before, but I think it should work.

**Comment by cah-prashanth-soma** [comment]
thanks. if you meant without suffix? yes I did. And nothing is logged. Nothing is getting hit.

**Comment by mekpavit** [comment]
@cah-prashanth-soma I've already tested dialogflow-integration with Azure Bot Service. It did work but it requires some changes on `server.js` since the Cloud Function works with only some project structure. Here is what I did:

1.  Move `botlib` folder to be in `skype`.
2. Update importing statement in `skype/server.js` to refer to the new location of `botlib`. For example, you have to change `const protoToJson = require('../botlib/proto_to_json.js');` to `const protoToJson = require('./botlib/proto_to_json.js');` (remove one dot).
3. Remove this code block
```
const listener = app.listen(port, () => {
  console.log('Your Skype integration server is listening on port '
      + listener.address().port);
});
```
4. change this code block:
```
module.exports = {
  convertToSkypeMessage
};
```
to this:
```
module.exports = {
  convertToSkypeMessage,
  app
};
```
5. Deploy to the Cloud Function with `nodejs12` runtime, `app` entry point and service account that you created according to the instruction. For example,
```
gcloud functions deploy you-function-name --runtime nodejs12 --service-account=some-service-acount-email@some-project-id.iam.gserviceaccount.com --entry-point app --trigger-http
```

**Comment by cah-prashanth-soma** [comment]
@mekpavit, it works. I thank you profusely for your quick and detailed response. Point 4 did the magic for me. (I have already implemented point 1 and 2 and redirected 3 to other port, but I was using convertToSkypeMessage as entry point ).

**Comment by mekpavit** [comment]
@cah-prashanth-soma You're welcome!!

**Comment by preethamjv** [comment]
@mekpavit what is the messaging endpoint for cloud run? I have set mine to https://skype-xxxxxxxxxx-uc.a.run.app, But my dialogflow intents still do not show up on Azure bot. can you pls help?

**Comment by mekpavit** [comment]
> @mekpavit what is the messaging endpoint for cloud run? I have set mine to https://skype-xxxxxxxxxx-uc.a.run.app, But my dialogflow intents still do not show up on Azure bot. can you pls help?

Can you show your Cloud Run log? I want to ensure that the Microsoft Bot Service can't access your Cloud Run.

**Comment by preethamjv** [comment]
@mekpavit I get a series of error messages in my logs
![image](https://user-images.githubusercontent.com/80092714/110317923-d2e6e700-8032-11eb-8373-47859cdfc344.png)
![image](https://user-images.githubusercontent.com/80092714/110317985-ee51f200-8032-11eb-9a62-2113a1e5cd11.png)
![image](https://user-images.githubusercontent.com/80092714/110318036-00339500-8033-11eb-83ef-bda99f200767.png)

**Comment by mekpavit** [comment]
> @mekpavit I get a series of error messages in my logs
> ![image](https://user-images.githubusercontent.com/80092714/110317923-d2e6e700-8032-11eb-8373-47859cdfc344.png)
> ![image](https://user-images.githubusercontent.com/80092714/110317985-ee51f200-8032-11eb-9a62-2113a1e5cd11.png)
> ![image](https://user-images.githubusercontent.com/80092714/110318036-00339500-8033-11eb-83ef-bda99f200767.png)

According to the logs, it looks like you misconfigure the microsoft secret. Can you show me your server.js file? Maybe take a screenshot around here:
![Screen Shot 2564-03-08 at 19 20 23](https://user-images.githubusercontent.com/21259908/110320731-57416600-8043-11eb-9c42-6566a138be39.png)

**Comment by preethamjv** [comment]
@mekpavit Thanks for your prompt follow-up, here is the screenshot
![image](https://user-images.githubusercontent.com/80092714/110321642-f82a2400-8037-11eb-90b4-be117bf5feeb.png)

**Comment by preethamjv** [comment]
@mekpavit thanks for your quick follow-up, here is the screenshot
![image](https://user-images.githubusercontent.com/80092714/110321846-40e1dd00-8038-11eb-91ab-99ad3e164e76.png)

**Comment by preethamjv** [comment]
@mekpavit thanks for your quick follow-up, here is the screenshot.
![image](https://user-images.githubusercontent.com/80092714/110322063-91593a80-8038-11eb-9635-9f0541f39342.png)

**Comment by preethamjv** [comment]
@mekpavit Thanks for your quick follow-up, here is the screenshot
![image](https://user-images.githubusercontent.com/80092714/110322217-cbc2d780-8038-11eb-87c9-558412d04b7d.png)
![image](https://user-images.githubusercontent.com/80092714/110322209-c5ccf680-8038-11eb-91e9-153ca5e67780.png)

**Comment by mekpavit** [comment]
@preethamjv Okay, you already set the `appId` and `appPassword`. Could you check whether the `appId` and `appPassword` in `server.js` are correct? (1. Is it really the appId of your chatbot? 2. Is the appId match the appPassword)

**Comment by preethamjv** [comment]
@mekpavit I have checked the app id and password, it was correct. I redeployed the code into a new cloud function, it worked!
Adding the missing steps in documentation:
On dialogflow webhook fulfillment section, we need to give the MS Azure endpoint URL:
![image](https://user-images.githubusercontent.com/80092714/110333911-2dd70900-8048-11eb-8ab3-c09b56d8c9e1.png)

In the Azure bot configuration section, replace the existing MS Azure endpoint URL with the URL of the Cloud Run service that we have created.
![image](https://user-images.githubusercontent.com/80092714/110334397-bc4b8a80-8048-11eb-9645-ab7c916dcc24.png)

Hope this helps someone!

@mekpavit thanks for your quick response!

**Comment by preethamjv** [comment]
@mekpavit just wanted to check, can we add google calendar schedule(book a slot) feature into this integration? Pls give your inputs, thanks in advance!

**Comment by mekpavit** [comment]
> @mekpavit just wanted to check, can we add google calendar schedule(book a slot) feature into this integration? Pls give your inputs, thanks in advance!

I'm not sure if I really understand your feature. if I guess it may be one of this:

1. When someone ask your chatbot to setup a meeting, you chatbot schedule a meeting on Google Calendar:
- IMO, this integration app should only concern about how to integrate between various messaging platform and Google's Dialogflow. If you want to add a feature like this, it might be better to add it in your bot handler app.

2. When someone schedule a meeting on the bot's Google Calendar, it triggers the Google's Dialogflow intent based on some properties on the meeting.
- This is possible since the Google Calendar API has a feature that let's an application watch for a change in a calendar. If this is what you want, you can take a look about the Google Calendar API [here](https://developers.google.com/calendar/v3/push) and develop the feature on this repository.

**Comment by ExceptionXD** [comment]
> @revs1 I did integrate the Dialogflow with Microsoft Teams about 4 months ago using the same approach as Skype., I think it is still working now. Have you tried integrating using the Skype approach mentioned [here](https://github.com/GoogleCloudPlatform/dialogflow-integrations/tree/master/skype). The key is that Dialogflow does not directly connect to Microsoft Teams, instead, it connects to Azure Bot Service and you integrate Azure Bot Service with Microsoft Teams channel just like [this](https://docs.microsoft.com/en-us/azure/bot-service/channel-connect-teams?view=azure-bot-service-4.0).

Hi, is there any video tutorial for the same, I am facing issues.

**Comment by mekpavit** [comment]
@ExceptionXD What's the issues you're facing?

**Comment by ExceptionXD** [comment]
@mekpavit So I followed all the steps and also got the URL but when i am keeping that as my messaging endpoint and testing web chat I am getting the following error :
There was an error sending this message to your bot: HTTP status code Unauthorized

**Comment by mekpavit** [comment]
> @mekpavit So I followed all the steps and also got the URL but when i am keeping that as my messaging endpoint and testing web chat I am getting the following error :
> There was an error sending this message to your bot: HTTP status code Unauthorized

Where did you get this error message? From Microsoft Teams web chat or from the logging page on GCP?

**Comment by ExceptionXD** [comment]
@mekpavit on Microsoft Team web chat

**Comment by mekpavit** [comment]
> @mekpavit on Microsoft Team web chat

So, the situation is that, when Microsoft Teams sends a HTTP request to your Cloud Run application, it responses back with 401 status code. One possibility that can be the root clause is that "allow unauthenticated invocations" setting on your Cloud Run application is set to "no".

Could you confirm that, when you deploying using `gcloud beta run deploy` command, you answer "y" when it is prompted to allow unauthenticated invocations?

**Comment by ExceptionXD** [comment]
Yes I had given 'y' as my response

**Comment by ExceptionXD** [comment]
@mekpavit the msg endpoint which i got, I am placing that in my web chat bot -> configurations -> messaging endpoint and then testing. This is what is mentioned right ?

**Comment by ExceptionXD** [comment]
Hey @mekpavit , @preethamjv  has mentioned that " I have checked the app id and password, it was correct. I redeployed the code into a new cloud run service, it worked!
Adding the missing steps in documentation:
On dialogflow webhook fulfillment section, we need to give the MS Azure endpoint URL:"

so do i need to do this ?

**Comment by cah-prashanth-soma** [comment]
Well.. 
1) Cloud run service end point URL has to be plugged in Bot framework messaging end point (configuration section)
2) if you have a cloud function that has the webhook handling functionality .. you can mention its trigger URL On you dialogflow webhook fulfillment section.

**Comment by ExceptionXD** [comment]
From where to get MS Azure end point URL ?

**Comment by mekpavit** [comment]
@ExceptionXD Okay, so, 401 response does not come from Cloud Run authentication. Cloud you show your application logs on Cloud Run? I want to confirm that whether the 401 response was from `BotFrameworkAdapter` or not.

**Comment by ExceptionXD** [comment]
![Screenshot (50)](https://user-images.githubusercontent.com/33571530/114127856-b501f000-9918-11eb-8f23-54906d533311.png)
![Screenshot (51)](https://user-images.githubusercontent.com/33571530/114127862-b6cbb380-9918-11eb-9120-80b93b81da36.png)

**Comment by mekpavit** [comment]
@ExceptionXD Ok. According to the logs, it seems like the service account of your application does not have a permission to use Dialogflow. Could you confirm that you've done "Service Account Setup (GCP)" section [here](https://github.com/GoogleCloudPlatform/dialogflow-integrations/blob/master/README.md). If you've already done this, please show the screenshot of IAM page on your GCP console, so I can ensure that you give the right permission to the service account.

**Comment by ExceptionXD** [comment]
![Screenshot (52)](https://user-images.githubusercontent.com/33571530/114129298-f0ea8480-991b-11eb-9bf0-f6824703131f.png)
![Screenshot (53)](https://user-images.githubusercontent.com/33571530/114129303-f2b44800-991b-11eb-9c4a-936187d6e736.png)
@mekpavit the second image has the permissions which are granted to me

**Comment by ExceptionXD** [comment]
@mekpavit I am using DialogFlowCX, so is the integration process different ?

**Comment by mekpavit** [comment]
> DialogFlowCX

After reading the API document of both Dialogflow ES and CSV, the API specification seems different. Since this integration application only supports Dialogflow ES, I think you cannot use Dialogflow CX here.

**Comment by kyooi2** [comment]
![image](https://user-images.githubusercontent.com/56020332/134454311-1ad0edec-4594-4f19-8168-775cf45973ea.png)

Hi @mekpavit, I follow the msteams integrations using cloud run, but facing the issue above. Can you assist to help?

**Comment by mekpavit** [comment]
According to your logs, the `response` object doesn't have `response.payload.fields.skype` field. So, when `convertToSkypeMessage` tried to get that field's value to convert to a valid MSTeam response, it encountered `Cannot read property 'structValue' of undefined` error.

I would suggest you to find out why Dialogflow responded you back with that `response` object. Do you use a webhook or just Dialogflow to process a message?
- If you use your own webhook, you can easily fix the HTTP response to Diagflow to include `payload.fields.skype` field
- If you use only Dialogflow, you might need to find a way to transform the HTTP response body to include `payload.fields.skype` field

**Comment by kyooi2** [comment]
@mekpavit Hi. I think i found out the things that i have missed out. I forgot to add in the response for skype, so when it route back to default response, it will take the default payload. This is what I encounter for the error. Thanks alot for helping.

![image](https://user-images.githubusercontent.com/56020332/134662785-f1ba9800-c0ee-49d5-adfb-254bd56467de.png)

**Comment by olivomarco** [comment]
Hi. Using knowledge from this issue I have recently created [this repo](https://github.com/olivomarco/dialogflow-teams-integration) where I have put all code and instructions needed to integrate bots in DialogFlow with Microsoft Teams.
HTH

**Comment by AdityaSinghania93** [comment]
Hi @olivomarco ,
I am getting error while trying to deploy the below command in GCP cloud function.

===================================
gcloud functions deploy demodialogflowteams
--runtime nodejs12
--service-account=[demodialogflowteams@demodialogflowteams.iam.gserviceaccount.com](mailto:demodialogflowteams@demodialogflowteams.iam.gserviceaccount.com)
--entry-point app
--trigger-http
--set-env-vars GOOGLE_PROJECT_ID="demodialogflowteams",MICROSOFT_APP_ID=$MICROSOFT_APP_ID,MICROSOFT_APP_PASSWORD=$MICROSOFT_APP_PASSWORD,MICROSOFT_TENANT_ID=$MICROSOFT_TENANT_ID
==================================
If you can please guide me where i am wrong to deploy this cloud function in GCP that connects our dialog flow with Microsoft teams for conversation

**Comment by AdityaSinghania93** [comment]
Hello @mekpavit 
Hope you doing great.
I am trying to integrate Google Dialog Flow with MS Teams but could not complete it.
I have created Google dialog Flow intents ( request & response ).
Created Azure Service Bot also & also followed the below link in order to compete the integration but it does not work.
I don't receive any response on MS teams platform the response that i have written in my Google Dialog flow.

https://github.com/olivomarco/dialogflow-teams-integration
If you can help me set up the integration of Google Dialog Flow with MS teams.
Almost 90 % work is completed not sure what is causing the error.
If you have any step by step to follow, if you can share it it will be big help also

**Comment by ghchinoy** [comment]
Please see a more recent integration in this repo https://github.com/GoogleCloudPlatform/dialogflow-integrations/tree/master/cx/azure-bot-service

**Comment by shahilnissam** [comment]
Have any one got this type of gateway timeout issue for dialogflow cx integration with azure bot service?
https://github.com/GoogleCloudPlatform/dialogflow-integrations/tree/master/cx/azure-bot-service
All of the env keys are correct as per the instruction.. but still I get this error.

**September 23, 2023 at 9:53 PM GMT+5:30
There was an error sending this message to your bot: HTTP status code GatewayTimeout
ca12f4b87b1ba4ae040098b5904c62e6
September 23, 2023 at 9:53 PM GMT+5:30
There was an error sending this message to your bot: HTTP status code GatewayTimeout
ed831e63a2ab1aa006481194303aa1c1**
